### ISSUE TITLE
Improve Activities page performance

### ISSUE THREAD

**Issue by zainfathoni** [senar-ai/web#25]
## Description

Testing for Reliable Web Apps

_Pengujian untuk Aplikasi Web yang Andal_

## Narrative

- **As a** visitor
- **I want** to load the /activities page quickly
- **so that** I can browse the list of activities smoothly

### Scenario 1: 

- **Given** 
- **and** 
- **when** 
- **then** 
- **and** 

### Image previews

<details>
<summary>Component name</summary>

#### Mobile view

</details>

### Code snippets

<details>
<summary>Component name</summary>

```jsx

```

</details>

## Tasks

- [ ] Write integration tests
- [ ] Write end-to-end-tests
- [ ] Audit web performance (especially the first page load)
- [ ] Implement virtualization for faster page load
