### ISSUE TITLE
Implement contribution form

### ISSUE THREAD

**Issue by zainfathoni** [senar-ai/web#26]
## Overview

Implement the contribution form to substitute the current Google Form implementation.

Some parts of this epic will be demonstrated in this **Testing for Reliable Web Apps** talk: [_Pengujian untuk Aplikasi Web yang Andal_](https://alamisharia.co.id/acara/pengujian-untuk-aplikasi-web-yang-andal/)

## Definition of Done

1. Implement a form to replace the [contribution form](https://senar.ai/go/form)
2. Implement a view to show the submitted form to the user
3. Write end-to-end tests to cover both implementations above

## Current Tasks

- [ ] Database integration
  - [ ] Compose SQLite database schema
  - [ ] Compose PostgreSQL database schema
- [ ] End-to-end test integration
  - [ ] Setup Playwright
  - [ ] Setup CI workflow for the end-to-end tests
- [ ] Unit & integration tests integration
  - [ ] Setup React Testing Library
  - [ ] Setup CI workflow for the unit & integration tests
- [ ] Implementation
  - [ ] Implement form page
  - [ ] Implement view page
- [ ] Tests
  - [ ] Write e2e tests
  - [ ] Write unit & integration tests
